services:
  dujiaoka:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: dujiaoka
    environment:
      - INSTALL=true  #安装时候需要设置为true，安装完成后后续运行需要设置为false
    volumes:
      - ./test/uploads:/dujiaoka/public/uploads
      - ./test/storage:/dujiaoka/storage
      - ./test/env.conf:/dujiaoka/.env
    ports:
      - 9999:80
    restart: always

  db:
    image: mariadb:focal
    container_name: dujiaoka-data
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=dujiaoka
      - MYSQL_PASSWORD=example
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: dujiaoka-redis
    restart: always
    volumes:
      - ./redis:/data